// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/DanielPopoola/ficmart-payment-gateway/internal/application"

	mock "github.com/stretchr/testify/mock"
)

// MockBankClient is an autogenerated mock type for the BankClient type
type MockBankClient struct {
	mock.Mock
}

type MockBankClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankClient) EXPECT() *MockBankClient_Expecter {
	return &MockBankClient_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Authorize(ctx context.Context, req application.BankAuthorizationRequest, idempotencyKey string) (*application.BankAuthorizationResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *application.BankAuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, application.BankAuthorizationRequest, string) (*application.BankAuthorizationResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, application.BankAuthorizationRequest, string) *application.BankAuthorizationResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankAuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, application.BankAuthorizationRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockBankClient_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - req application.BankAuthorizationRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Authorize(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Authorize_Call {
	return &MockBankClient_Authorize_Call{Call: _e.mock.On("Authorize", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Authorize_Call) Run(run func(ctx context.Context, req application.BankAuthorizationRequest, idempotencyKey string)) *MockBankClient_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(application.BankAuthorizationRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Authorize_Call) Return(_a0 *application.BankAuthorizationResponse, _a1 error) *MockBankClient_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Authorize_Call) RunAndReturn(run func(context.Context, application.BankAuthorizationRequest, string) (*application.BankAuthorizationResponse, error)) *MockBankClient_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// Capture provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Capture(ctx context.Context, req application.BankCaptureRequest, idempotencyKey string) (*application.BankCaptureResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 *application.BankCaptureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, application.BankCaptureRequest, string) (*application.BankCaptureResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, application.BankCaptureRequest, string) *application.BankCaptureResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankCaptureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, application.BankCaptureRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type MockBankClient_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - ctx context.Context
//   - req application.BankCaptureRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Capture(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Capture_Call {
	return &MockBankClient_Capture_Call{Call: _e.mock.On("Capture", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Capture_Call) Run(run func(ctx context.Context, req application.BankCaptureRequest, idempotencyKey string)) *MockBankClient_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(application.BankCaptureRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Capture_Call) Return(_a0 *application.BankCaptureResponse, _a1 error) *MockBankClient_Capture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Capture_Call) RunAndReturn(run func(context.Context, application.BankCaptureRequest, string) (*application.BankCaptureResponse, error)) *MockBankClient_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorization provides a mock function with given fields: ctx, authID
func (_m *MockBankClient) GetAuthorization(ctx context.Context, authID string) (*application.BankAuthorizationResponse, error) {
	ret := _m.Called(ctx, authID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorization")
	}

	var r0 *application.BankAuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*application.BankAuthorizationResponse, error)); ok {
		return rf(ctx, authID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *application.BankAuthorizationResponse); ok {
		r0 = rf(ctx, authID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankAuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_GetAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorization'
type MockBankClient_GetAuthorization_Call struct {
	*mock.Call
}

// GetAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - authID string
func (_e *MockBankClient_Expecter) GetAuthorization(ctx interface{}, authID interface{}) *MockBankClient_GetAuthorization_Call {
	return &MockBankClient_GetAuthorization_Call{Call: _e.mock.On("GetAuthorization", ctx, authID)}
}

func (_c *MockBankClient_GetAuthorization_Call) Run(run func(ctx context.Context, authID string)) *MockBankClient_GetAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBankClient_GetAuthorization_Call) Return(_a0 *application.BankAuthorizationResponse, _a1 error) *MockBankClient_GetAuthorization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_GetAuthorization_Call) RunAndReturn(run func(context.Context, string) (*application.BankAuthorizationResponse, error)) *MockBankClient_GetAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// GetCapture provides a mock function with given fields: ctx, captureID
func (_m *MockBankClient) GetCapture(ctx context.Context, captureID string) (*application.BankCaptureResponse, error) {
	ret := _m.Called(ctx, captureID)

	if len(ret) == 0 {
		panic("no return value specified for GetCapture")
	}

	var r0 *application.BankCaptureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*application.BankCaptureResponse, error)); ok {
		return rf(ctx, captureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *application.BankCaptureResponse); ok {
		r0 = rf(ctx, captureID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankCaptureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, captureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_GetCapture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapture'
type MockBankClient_GetCapture_Call struct {
	*mock.Call
}

// GetCapture is a helper method to define mock.On call
//   - ctx context.Context
//   - captureID string
func (_e *MockBankClient_Expecter) GetCapture(ctx interface{}, captureID interface{}) *MockBankClient_GetCapture_Call {
	return &MockBankClient_GetCapture_Call{Call: _e.mock.On("GetCapture", ctx, captureID)}
}

func (_c *MockBankClient_GetCapture_Call) Run(run func(ctx context.Context, captureID string)) *MockBankClient_GetCapture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBankClient_GetCapture_Call) Return(_a0 *application.BankCaptureResponse, _a1 error) *MockBankClient_GetCapture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_GetCapture_Call) RunAndReturn(run func(context.Context, string) (*application.BankCaptureResponse, error)) *MockBankClient_GetCapture_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefund provides a mock function with given fields: ctx, refundID
func (_m *MockBankClient) GetRefund(ctx context.Context, refundID string) (*application.BankRefundResponse, error) {
	ret := _m.Called(ctx, refundID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefund")
	}

	var r0 *application.BankRefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*application.BankRefundResponse, error)); ok {
		return rf(ctx, refundID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *application.BankRefundResponse); ok {
		r0 = rf(ctx, refundID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankRefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refundID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_GetRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefund'
type MockBankClient_GetRefund_Call struct {
	*mock.Call
}

// GetRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - refundID string
func (_e *MockBankClient_Expecter) GetRefund(ctx interface{}, refundID interface{}) *MockBankClient_GetRefund_Call {
	return &MockBankClient_GetRefund_Call{Call: _e.mock.On("GetRefund", ctx, refundID)}
}

func (_c *MockBankClient_GetRefund_Call) Run(run func(ctx context.Context, refundID string)) *MockBankClient_GetRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBankClient_GetRefund_Call) Return(_a0 *application.BankRefundResponse, _a1 error) *MockBankClient_GetRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_GetRefund_Call) RunAndReturn(run func(context.Context, string) (*application.BankRefundResponse, error)) *MockBankClient_GetRefund_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Refund(ctx context.Context, req application.BankRefundRequest, idempotencyKey string) (*application.BankRefundResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 *application.BankRefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, application.BankRefundRequest, string) (*application.BankRefundResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, application.BankRefundRequest, string) *application.BankRefundResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankRefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, application.BankRefundRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockBankClient_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - req application.BankRefundRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Refund(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Refund_Call {
	return &MockBankClient_Refund_Call{Call: _e.mock.On("Refund", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Refund_Call) Run(run func(ctx context.Context, req application.BankRefundRequest, idempotencyKey string)) *MockBankClient_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(application.BankRefundRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Refund_Call) Return(_a0 *application.BankRefundResponse, _a1 error) *MockBankClient_Refund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Refund_Call) RunAndReturn(run func(context.Context, application.BankRefundRequest, string) (*application.BankRefundResponse, error)) *MockBankClient_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// Void provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Void(ctx context.Context, req application.BankVoidRequest, idempotencyKey string) (*application.BankVoidResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 *application.BankVoidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, application.BankVoidRequest, string) (*application.BankVoidResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, application.BankVoidRequest, string) *application.BankVoidResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.BankVoidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, application.BankVoidRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Void_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Void'
type MockBankClient_Void_Call struct {
	*mock.Call
}

// Void is a helper method to define mock.On call
//   - ctx context.Context
//   - req application.BankVoidRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Void(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Void_Call {
	return &MockBankClient_Void_Call{Call: _e.mock.On("Void", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Void_Call) Run(run func(ctx context.Context, req application.BankVoidRequest, idempotencyKey string)) *MockBankClient_Void_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(application.BankVoidRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Void_Call) Return(_a0 *application.BankVoidResponse, _a1 error) *MockBankClient_Void_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Void_Call) RunAndReturn(run func(context.Context, application.BankVoidRequest, string) (*application.BankVoidResponse, error)) *MockBankClient_Void_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBankClient creates a new instance of MockBankClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankClient {
	mock := &MockBankClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
