# .mockery.yaml
with-expecter: true
dir: "internal/mocks"
packages:
  github.com/DanielPopoola/ficmart-payment-gateway/internal/application:
    config:
      outpkg: mocks
    interfaces:
      BankClient: