# .mockery.yaml
with-expecter: true

packages:
  github.com/DanielPopoola/ficmart-payment-gateway/internal/infrastructure/bank:
    config:
      outpkg: mocks
      dir: internal/infrastructure/bank/mocks
    interfaces:
      BankClient:
