// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/DanielPopoola/ficmart-payment-gateway/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/DanielPopoola/ficmart-payment-gateway/internal/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// CreateIdempotencyKey provides a mock function with given fields: ctx, key
func (_m *PaymentRepository) CreateIdempotencyKey(ctx context.Context, key *domain.IdempotencyKey) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CreateIdempotencyKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IdempotencyKey) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePayment provides a mock function with given fields: ctx, payment
func (_m *PaymentRepository) CreatePayment(ctx context.Context, payment *domain.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCustomerID provides a mock function with given fields: ctx, customerID, limit, offset
func (_m *PaymentRepository) FindByCustomerID(ctx context.Context, customerID string, limit int, offset int) ([]*domain.Payment, error) {
	ret := _m.Called(ctx, customerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByCustomerID")
	}

	var r0 []*domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Payment, error)); ok {
		return rf(ctx, customerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Payment); ok {
		r0 = rf(ctx, customerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, customerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PaymentRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *PaymentRepository) FindByIDForUpdate(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdempotencyKey provides a mock function with given fields: ctx, key
func (_m *PaymentRepository) FindByIdempotencyKey(ctx context.Context, key string) (*domain.Payment, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdempotencyKey")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByOrderID provides a mock function with given fields: ctx, orderID
func (_m *PaymentRepository) FindByOrderID(ctx context.Context, orderID string) (*domain.Payment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindIdempotencyKeyRecord provides a mock function with given fields: ctx, key
func (_m *PaymentRepository) FindIdempotencyKeyRecord(ctx context.Context, key string) (*domain.IdempotencyKey, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindIdempotencyKeyRecord")
	}

	var r0 *domain.IdempotencyKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.IdempotencyKey, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.IdempotencyKey); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IdempotencyKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPendingPayments provides a mock function with given fields: ctx, olderThan, limit
func (_m *PaymentRepository) FindPendingPayments(ctx context.Context, olderThan time.Duration, limit int) ([]*domain.PendingPaymentCheck, error) {
	ret := _m.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingPayments")
	}

	var r0 []*domain.PendingPaymentCheck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, int) ([]*domain.PendingPaymentCheck, error)); ok {
		return rf(ctx, olderThan, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, int) []*domain.PendingPaymentCheck); ok {
		r0 = rf(ctx, olderThan, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PendingPaymentCheck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = rf(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateIdempotencyKey provides a mock function with given fields: ctx, key
func (_m *PaymentRepository) UpdateIdempotencyKey(ctx context.Context, key *domain.IdempotencyKey) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIdempotencyKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IdempotencyKey) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePayment provides a mock function with given fields: ctx, payment
func (_m *PaymentRepository) UpdatePayment(ctx context.Context, payment *domain.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *PaymentRepository) WithTx(ctx context.Context, fn func(repository.PaymentRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(repository.PaymentRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
