// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseErrorCode.
const (
	AMOUNTMISMATCH           ErrorResponseErrorCode = "AMOUNT_MISMATCH"
	DUPLICATEBUSINESSREQUEST ErrorResponseErrorCode = "DUPLICATE_BUSINESS_REQUEST"
	DUPLICATEIDEMPOTENCYKEY  ErrorResponseErrorCode = "DUPLICATE_IDEMPOTENCY_KEY"
	IDEMPOTENCYMISMATCH      ErrorResponseErrorCode = "IDEMPOTENCY_MISMATCH"
	INTERNALERROR            ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDAMOUNT            ErrorResponseErrorCode = "INVALID_AMOUNT"
	INVALIDSTATE             ErrorResponseErrorCode = "INVALID_STATE"
	INVALIDTRANSITION        ErrorResponseErrorCode = "INVALID_TRANSITION"
	MISSINGDEPENDENCY        ErrorResponseErrorCode = "MISSING_DEPENDENCY"
	MISSINGREQUIREDFIELD     ErrorResponseErrorCode = "MISSING_REQUIRED_FIELD"
	PAYMENTEXPIRED           ErrorResponseErrorCode = "PAYMENT_EXPIRED"
	PAYMENTNOTFOUND          ErrorResponseErrorCode = "PAYMENT_NOT_FOUND"
	REQUESTPROCESSING        ErrorResponseErrorCode = "REQUEST_PROCESSING"
	TIMEOUT                  ErrorResponseErrorCode = "TIMEOUT"
	VALIDATIONERROR          ErrorResponseErrorCode = "VALIDATION_ERROR"
)

// Defines values for PaymentStatus.
const (
	AUTHORIZED PaymentStatus = "AUTHORIZED"
	CAPTURED   PaymentStatus = "CAPTURED"
	EXPIRED    PaymentStatus = "EXPIRED"
	FAILED     PaymentStatus = "FAILED"
	PENDING    PaymentStatus = "PENDING"
	REFUNDED   PaymentStatus = "REFUNDED"
	VOIDED     PaymentStatus = "VOIDED"
)

// AuthorizeRequest defines model for AuthorizeRequest.
type AuthorizeRequest struct {
	// Amount Amount in cents (e.g., 5000 = $50.00)
	Amount int64 `json:"amount"`

	// CardNumber Card number (13-19 digits)
	CardNumber string `json:"card_number"`

	// CustomerId Customer identifier from FicMart
	CustomerId string `json:"customer_id"`

	// Cvv Card verification value (3-4 digits)
	Cvv string `json:"cvv"`

	// ExpiryMonth Card expiry month (1-12)
	ExpiryMonth int `json:"expiry_month"`

	// ExpiryYear Card expiry year (YYYY)
	ExpiryYear int `json:"expiry_year"`

	// OrderId Unique order identifier from FicMart
	OrderId string `json:"order_id"`
}

// CaptureRequest defines model for CaptureRequest.
type CaptureRequest struct {
	// Amount Amount to capture in cents (must match authorized amount)
	Amount int64 `json:"amount"`

	// PaymentId The payment ID to capture
	PaymentId openapi_types.UUID `json:"payment_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Machine-readable error code
		Code ErrorResponseErrorCode `json:"code"`

		// Message Human-readable error message
		Message string `json:"message"`
	} `json:"error,omitempty,omitzero"`
	Success bool `json:"success,omitempty,omitzero"`
}

// ErrorResponseErrorCode Machine-readable error code
type ErrorResponseErrorCode string

// Payment defines model for Payment.
type Payment struct {
	// AmountCents Amount in cents
	AmountCents int64 `json:"amount_cents"`

	// AttemptCount Number of retry attempts
	AttemptCount int `json:"attempt_count"`

	// AuthorizedAt When payment was authorized
	AuthorizedAt time.Time `json:"authorized_at,omitzero"`

	// BankAuthId Bank's authorization ID
	BankAuthId string `json:"bank_auth_id,omitzero"`

	// BankCaptureId Bank's capture ID
	BankCaptureId string `json:"bank_capture_id,omitzero"`

	// BankRefundId Bank's refund ID
	BankRefundId string `json:"bank_refund_id,omitzero"`

	// BankVoidId Bank's void ID
	BankVoidId string `json:"bank_void_id,omitzero"`

	// CapturedAt When payment was captured
	CapturedAt time.Time `json:"captured_at,omitzero"`

	// CreatedAt When payment was created
	CreatedAt time.Time `json:"created_at"`

	// Currency Currency code
	Currency string `json:"currency"`

	// CustomerId Customer ID from FicMart
	CustomerId string `json:"customer_id"`

	// ExpiresAt When authorization expires (7 days from authorization)
	ExpiresAt time.Time `json:"expires_at,omitzero"`

	// Id Unique payment identifier
	Id openapi_types.UUID `json:"id"`

	// NextRetryAt When next retry is scheduled
	NextRetryAt time.Time `json:"next_retry_at,omitzero"`

	// OrderId Order ID from FicMart
	OrderId string `json:"order_id"`

	// RefundedAt When payment was refunded
	RefundedAt time.Time `json:"refunded_at,omitzero"`

	// Status Current payment status
	Status PaymentStatus `json:"status"`

	// VoidedAt When payment was voided
	VoidedAt time.Time `json:"voided_at,omitzero"`
}

// PaymentStatus Current payment status
type PaymentStatus string

// PaymentResponse defines model for PaymentResponse.
type PaymentResponse struct {
	Data Payment `json:"data,omitempty,omitzero"`

	// Success Whether the request succeeded
	Success bool `json:"success,omitempty,omitzero"`
}

// RefundRequest defines model for RefundRequest.
type RefundRequest struct {
	// Amount Amount to refund in cents (must match captured amount)
	Amount int64 `json:"amount"`

	// PaymentId The payment ID to refund
	PaymentId openapi_types.UUID `json:"payment_id"`
}

// VoidRequest defines model for VoidRequest.
type VoidRequest struct {
	// PaymentId The payment ID to void
	PaymentId openapi_types.UUID `json:"payment_id"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// AuthorizePaymentParams defines parameters for AuthorizePayment.
type AuthorizePaymentParams struct {
	// IdempotencyKey Unique key to ensure request idempotency. Same key with same request
	// returns cached response. Prevents duplicate charges.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CapturePaymentParams defines parameters for CapturePayment.
type CapturePaymentParams struct {
	// IdempotencyKey Unique key to ensure request idempotency. Same key with same request
	// returns cached response. Prevents duplicate charges.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetPaymentsByCustomerParams defines parameters for GetPaymentsByCustomer.
type GetPaymentsByCustomerParams struct {
	// Limit Maximum number of payments to return
	Limit int `form:"limit,omitempty" json:"limit,omitempty,omitzero"`

	// Offset Number of payments to skip
	Offset int `form:"offset,omitempty" json:"offset,omitempty,omitzero"`
}

// RefundPaymentParams defines parameters for RefundPayment.
type RefundPaymentParams struct {
	// IdempotencyKey Unique key to ensure request idempotency. Same key with same request
	// returns cached response. Prevents duplicate charges.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// VoidPaymentParams defines parameters for VoidPayment.
type VoidPaymentParams struct {
	// IdempotencyKey Unique key to ensure request idempotency. Same key with same request
	// returns cached response. Prevents duplicate charges.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AuthorizePaymentJSONRequestBody defines body for AuthorizePayment for application/json ContentType.
type AuthorizePaymentJSONRequestBody = AuthorizeRequest

// CapturePaymentJSONRequestBody defines body for CapturePayment for application/json ContentType.
type CapturePaymentJSONRequestBody = CaptureRequest

// RefundPaymentJSONRequestBody defines body for RefundPayment for application/json ContentType.
type RefundPaymentJSONRequestBody = RefundRequest

// VoidPaymentJSONRequestBody defines body for VoidPayment for application/json ContentType.
type VoidPaymentJSONRequestBody = VoidRequest
