//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authorize Payment
	// (POST /authorize)
	AuthorizePayment(w http.ResponseWriter, r *http.Request, params AuthorizePaymentParams)
	// Capture Payment
	// (POST /capture)
	CapturePayment(w http.ResponseWriter, r *http.Request, params CapturePaymentParams)
	// List Customer Payments
	// (GET /payments/customer/{customerID})
	GetPaymentsByCustomer(w http.ResponseWriter, r *http.Request, customerID string, params GetPaymentsByCustomerParams)
	// Get Payment by Order ID
	// (GET /payments/order/{orderID})
	GetPaymentByOrder(w http.ResponseWriter, r *http.Request, orderID string)
	// Refund Payment
	// (POST /refund)
	RefundPayment(w http.ResponseWriter, r *http.Request, params RefundPaymentParams)
	// Void Authorization
	// (POST /void)
	VoidPayment(w http.ResponseWriter, r *http.Request, params VoidPaymentParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthorizePayment operation middleware
func (siw *ServerInterfaceWrapper) AuthorizePayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthorizePaymentParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthorizePayment(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CapturePayment operation middleware
func (siw *ServerInterfaceWrapper) CapturePayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CapturePaymentParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CapturePayment(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentsByCustomer operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentsByCustomer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID string

	err = runtime.BindStyledParameterWithOptions("simple", "customerID", r.PathValue("customerID"), &customerID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPaymentsByCustomerParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentsByCustomer(w, r, customerID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentByOrder operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentByOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID string

	err = runtime.BindStyledParameterWithOptions("simple", "orderID", r.PathValue("orderID"), &orderID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentByOrder(w, r, orderID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefundPayment operation middleware
func (siw *ServerInterfaceWrapper) RefundPayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefundPaymentParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefundPayment(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VoidPayment operation middleware
func (siw *ServerInterfaceWrapper) VoidPayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params VoidPaymentParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VoidPayment(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/authorize", wrapper.AuthorizePayment)
	m.HandleFunc("POST "+options.BaseURL+"/capture", wrapper.CapturePayment)
	m.HandleFunc("GET "+options.BaseURL+"/payments/customer/{customerID}", wrapper.GetPaymentsByCustomer)
	m.HandleFunc("GET "+options.BaseURL+"/payments/order/{orderID}", wrapper.GetPaymentByOrder)
	m.HandleFunc("POST "+options.BaseURL+"/refund", wrapper.RefundPayment)
	m.HandleFunc("POST "+options.BaseURL+"/void", wrapper.VoidPayment)

	return m
}

type AuthorizePaymentRequestObject struct {
	Params AuthorizePaymentParams
	Body   *AuthorizePaymentJSONRequestBody
}

type AuthorizePaymentResponseObject interface {
	VisitAuthorizePaymentResponse(w http.ResponseWriter) error
}

type AuthorizePayment201JSONResponse PaymentResponse

func (response AuthorizePayment201JSONResponse) VisitAuthorizePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AuthorizePayment202JSONResponse ErrorResponse

func (response AuthorizePayment202JSONResponse) VisitAuthorizePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type AuthorizePayment400JSONResponse ErrorResponse

func (response AuthorizePayment400JSONResponse) VisitAuthorizePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthorizePayment409JSONResponse ErrorResponse

func (response AuthorizePayment409JSONResponse) VisitAuthorizePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AuthorizePayment500JSONResponse ErrorResponse

func (response AuthorizePayment500JSONResponse) VisitAuthorizePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CapturePaymentRequestObject struct {
	Params CapturePaymentParams
	Body   *CapturePaymentJSONRequestBody
}

type CapturePaymentResponseObject interface {
	VisitCapturePaymentResponse(w http.ResponseWriter) error
}

type CapturePayment200JSONResponse PaymentResponse

func (response CapturePayment200JSONResponse) VisitCapturePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CapturePayment400JSONResponse ErrorResponse

func (response CapturePayment400JSONResponse) VisitCapturePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CapturePayment404JSONResponse ErrorResponse

func (response CapturePayment404JSONResponse) VisitCapturePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CapturePayment409JSONResponse ErrorResponse

func (response CapturePayment409JSONResponse) VisitCapturePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetPaymentsByCustomerRequestObject struct {
	CustomerID string `json:"customerID"`
	Params     GetPaymentsByCustomerParams
}

type GetPaymentsByCustomerResponseObject interface {
	VisitGetPaymentsByCustomerResponse(w http.ResponseWriter) error
}

type GetPaymentsByCustomer200JSONResponse struct {
	Data    []Payment `json:"data,omitempty,omitzero"`
	Success bool      `json:"success,omitempty,omitzero"`
}

func (response GetPaymentsByCustomer200JSONResponse) VisitGetPaymentsByCustomerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPaymentByOrderRequestObject struct {
	OrderID string `json:"orderID"`
}

type GetPaymentByOrderResponseObject interface {
	VisitGetPaymentByOrderResponse(w http.ResponseWriter) error
}

type GetPaymentByOrder200JSONResponse PaymentResponse

func (response GetPaymentByOrder200JSONResponse) VisitGetPaymentByOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPaymentByOrder404JSONResponse ErrorResponse

func (response GetPaymentByOrder404JSONResponse) VisitGetPaymentByOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RefundPaymentRequestObject struct {
	Params RefundPaymentParams
	Body   *RefundPaymentJSONRequestBody
}

type RefundPaymentResponseObject interface {
	VisitRefundPaymentResponse(w http.ResponseWriter) error
}

type RefundPayment200JSONResponse PaymentResponse

func (response RefundPayment200JSONResponse) VisitRefundPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefundPayment400JSONResponse ErrorResponse

func (response RefundPayment400JSONResponse) VisitRefundPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RefundPayment404JSONResponse ErrorResponse

func (response RefundPayment404JSONResponse) VisitRefundPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RefundPayment409JSONResponse ErrorResponse

func (response RefundPayment409JSONResponse) VisitRefundPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type VoidPaymentRequestObject struct {
	Params VoidPaymentParams
	Body   *VoidPaymentJSONRequestBody
}

type VoidPaymentResponseObject interface {
	VisitVoidPaymentResponse(w http.ResponseWriter) error
}

type VoidPayment200JSONResponse PaymentResponse

func (response VoidPayment200JSONResponse) VisitVoidPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VoidPayment400JSONResponse ErrorResponse

func (response VoidPayment400JSONResponse) VisitVoidPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type VoidPayment404JSONResponse ErrorResponse

func (response VoidPayment404JSONResponse) VisitVoidPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type VoidPayment409JSONResponse ErrorResponse

func (response VoidPayment409JSONResponse) VisitVoidPaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authorize Payment
	// (POST /authorize)
	AuthorizePayment(ctx context.Context, request AuthorizePaymentRequestObject) (AuthorizePaymentResponseObject, error)
	// Capture Payment
	// (POST /capture)
	CapturePayment(ctx context.Context, request CapturePaymentRequestObject) (CapturePaymentResponseObject, error)
	// List Customer Payments
	// (GET /payments/customer/{customerID})
	GetPaymentsByCustomer(ctx context.Context, request GetPaymentsByCustomerRequestObject) (GetPaymentsByCustomerResponseObject, error)
	// Get Payment by Order ID
	// (GET /payments/order/{orderID})
	GetPaymentByOrder(ctx context.Context, request GetPaymentByOrderRequestObject) (GetPaymentByOrderResponseObject, error)
	// Refund Payment
	// (POST /refund)
	RefundPayment(ctx context.Context, request RefundPaymentRequestObject) (RefundPaymentResponseObject, error)
	// Void Authorization
	// (POST /void)
	VoidPayment(ctx context.Context, request VoidPaymentRequestObject) (VoidPaymentResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AuthorizePayment operation middleware
func (sh *strictHandler) AuthorizePayment(w http.ResponseWriter, r *http.Request, params AuthorizePaymentParams) {
	var request AuthorizePaymentRequestObject

	request.Params = params

	var body AuthorizePaymentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthorizePayment(ctx, request.(AuthorizePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthorizePayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthorizePaymentResponseObject); ok {
		if err := validResponse.VisitAuthorizePaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CapturePayment operation middleware
func (sh *strictHandler) CapturePayment(w http.ResponseWriter, r *http.Request, params CapturePaymentParams) {
	var request CapturePaymentRequestObject

	request.Params = params

	var body CapturePaymentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CapturePayment(ctx, request.(CapturePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CapturePayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CapturePaymentResponseObject); ok {
		if err := validResponse.VisitCapturePaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPaymentsByCustomer operation middleware
func (sh *strictHandler) GetPaymentsByCustomer(w http.ResponseWriter, r *http.Request, customerID string, params GetPaymentsByCustomerParams) {
	var request GetPaymentsByCustomerRequestObject

	request.CustomerID = customerID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPaymentsByCustomer(ctx, request.(GetPaymentsByCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPaymentsByCustomer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPaymentsByCustomerResponseObject); ok {
		if err := validResponse.VisitGetPaymentsByCustomerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPaymentByOrder operation middleware
func (sh *strictHandler) GetPaymentByOrder(w http.ResponseWriter, r *http.Request, orderID string) {
	var request GetPaymentByOrderRequestObject

	request.OrderID = orderID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPaymentByOrder(ctx, request.(GetPaymentByOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPaymentByOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPaymentByOrderResponseObject); ok {
		if err := validResponse.VisitGetPaymentByOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefundPayment operation middleware
func (sh *strictHandler) RefundPayment(w http.ResponseWriter, r *http.Request, params RefundPaymentParams) {
	var request RefundPaymentRequestObject

	request.Params = params

	var body RefundPaymentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefundPayment(ctx, request.(RefundPaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefundPayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefundPaymentResponseObject); ok {
		if err := validResponse.VisitRefundPaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VoidPayment operation middleware
func (sh *strictHandler) VoidPayment(w http.ResponseWriter, r *http.Request, params VoidPaymentParams) {
	var request VoidPaymentRequestObject

	request.Params = params

	var body VoidPaymentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VoidPayment(ctx, request.(VoidPaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VoidPayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VoidPaymentResponseObject); ok {
		if err := validResponse.VisitVoidPaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
