// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa63IaRxZ+la5OqtapGtCAkGNTtT+whB0qEigIeVeOtKQ1c4COZnom3T2KiUt/9wH2",
	"EfdJtvo2FxgQkm/aKvuPBfScPn2u3/l6PuAgidOEAZMCdz/glHASgwSuPw1CiNNEAguWP8NSfROCCDhN",
	"JU0Y7uJzRv/IAN3AEskEARMZB8ThjwyERLR4uInOSGzW/UnlAgn1ya27ZBxkxplAAQkWECIOIk2YgCY6",
	"5XCrNENhlkY0IBJQsCB8DqJ5ybCH4T2J0whwF6vNGgcHPrzo+H4D2i+vG51W2GmQH1vPG53O8+cHB52O",
	"7/s+9jBVqi+AhMCxhxmJlYDSURvqrB5W+lEOIe5KnoGHRbCAmCgjxOT9MbC5XOBu++DAwzFl7nPLw3KZ",
	"KoFCcsrm+O7uzj2qTdrL5CLh9C8Ym+Nro/MkBS4p6BUkTjIm143d098jylCgbfIMmvOmhw5830d/R98f",
	"+E3f/6FsFPWLh2cJj4lUJmLyeQdrbWmcxWVdKZMwB47vPBwQHk5ZFl8DX1fhkPAQmR/Rs9Z+o/UShXRO",
	"pajsizut6j/s4ZRICVzJ+NflZfihte+1Xt59j9es5eEgEzKJgU9pWKOA/VEFF5N0RoGjGU9i9JoGJ4TL",
	"ihpKUqNz8Lx2l9vbDce7BU5nKtZowtAtiTJAz/YbndqDttr762fb9zr1J4P3KeXLaZwwFSm1m5slSC9B",
	"z1qNVruyYavtqeCz7mvf50u74RII376fWoGeXVxcXFS2a/v7fmmPtt/u1G2T8HCDu2x90At2cple2TBm",
	"Xc2jckb+WmxajRjPpU81ko3DV1xQNdBVvmNy/TsEUp3skKQy449OVZmgwEgoZW2cCYliIoMFIq4WhMhI",
	"+vj0TckyBiZrvTFZALK/o8FRSbuKC3YsorleWabNvt1bJbVyD9UZvM95wse2/q/bG9TP618HSQjrxz0h",
	"wYIyaHAgIbmOAOmnkV7sYWDKhr/iwfBt73hwNJ2Me8OzwWQwGmIPn/YuTvrDybT/z9PBuH9U+mY4mkxf",
	"j86H6jv3aO9kdD6cYA8fnZ8eDw57k/50cNQ/OR1N+sPDi+nP/Qvs4XH/l/P+2WR6Oh4d9s/OBsM32MMn",
	"A/3XVP2oNpq+HvSPjyqSXp2fDYb9s7OpFVDa92zSm/Sxh83+05PB2UlvcvhTSe5R/7Q/PFJaqMdKOpXW",
	"TgYn/dG5kqul9pQJpv3xeDTWW03642Hv2H5xVVPVYhCCzGvs/1MWE7Zqfbf6voCxXnLL62JFZEEAwsSF",
	"i94ZiQTka6+TJALCtPC1x09NSG5K6mngINHWLoxrMnQ9K1WDiFM5DerLxdB01GSGOEi+RHa5qJeVF40p",
	"qZH1jwWwPMv/JKJUZMq6hkRCQ9JYGZllUaRc5IDOmouvCbuZKjm1ZeUVYTd/K/YxjXNwtLNgW4S2yXZV",
	"9AFSOcwyFm4TalY8ROZtQrdKVL/vKM+eaEcfutWP9mDAgciddzOLN21Wg9g4V7i5Dq6ZX/Kim3eZ87Oj",
	"x4O/wdEqgqjHWiA2H7garnY5evYjCslSGPGVJT882vZbgJGzegGN7u+sHmbwXk51pdh8PLXGVhMqkJo/",
	"wiz6iADajPFGGtzt4BKTb7sGoVv9aI2FJDITm2JS5pvZdQUiUC3TtOfe+eSn0XjwTiOAw97p5NyAgde9",
	"wbH+Y9x/fT480n++HQ3MHw4z1PVKVSB2NYBZ+8jjr3RTHUf3IOap62d5Ouc2rNSP1W52tbm3bgZyIZF6",
	"kv6ewwx38Xd7BQuxZ4flPdegq61+zWpyARzJRcEn6MVgbLcLEBjrSPsIjG8bSS3Ed5X7KwF8o9rTwfdv",
	"E7rZ0g87msqPL3qw9fOoxZTNEjODMEkCfSrLKPVOB+gsS9OE66NXz2ODG82JhD/JEqnFs4SjlCcq0imb",
	"IzW/ujMLJBc8yeYLRFCcBDdI4RG1SCyFhLh5yS7Zd98hJ/WYziBYBhFcsgay9Qz999//QUVF0x9dTdMf",
	"XDG75xlT6FYXmZJo1ShxaZesF0UozqTtsyxME6qT5HR0NvkBWVsjwtBvKxTcb8hwdMrZqSECSzygChwt",
	"UzQv2RgybTJVBkSFacy/cdXBcY3qh1W+UXOKkkodTraT5TZ9U3gKe/gWuDCebDX9pq9bZAqMpBR38X7T",
	"b1piaKEjey8H4TrOE1FTT8YggN+CQCpjBUoYIsjVaQ2BedhEh7oOC0QK6MByP6hqDR66ZG5+WAE5uUFU",
	"8HiIsBBJTpig2ozKzCVXJ9z6VMdWrxYtkZkEjixkojPEEpkXPGPM3EuDUGWEs4Ir7V6Fb/61vh8US/ZW",
	"+Oi7K5OsIOSrJFy6NLRTHUlNrNCE7f0ulI3zQVE75ZoIGqg/RBbHhC81jhc0qFpN+ZpEGZRbgSncFaa0",
	"jvOsgNkyG6nJR0seVknBVnuFtTMUXIG+SgxZiVm+r5Wukc531TqnMIT+wiSCNk/bbz3QoKVJs/uhsJrr",
	"9dW52thwZTD218Zb3PbbnYbfarQOJi2/u+93/dY7vDqS6qca5DowNi1POzUC/HdllONmkY3eKo8SubR2",
	"u6KOfmbX64ciiKc3sHSXFzewtMRnrbcLQFuFpVkabjtr610FP2lH7x43qzhOP1rfyEpcpt1tlkXRUu3e",
	"8f0HRhJltySi4bTAXnk05RSgIf3WSbicj3JSLPRCjZbvV4yhyaIHWKNKTtbYYmA3dL2mVNy0GV480AxW",
	"zlRh/iTbboeCxisMkOtRgAolKkRK2Ge1hK0z1e06/ssHGiBv99Nr1eBBiCkv0ONGW2xlTwvzFGDCSc89",
	"p6BYnnumcar8VAWhxm7VnI6p0Nh/e9jWk7Gl4C0kajTDIRMQGlVCOpuBHWLLEfb5/VmGpwmbRTSQCim4",
	"TNMIRGlysFPKf7K0k8AZiZAGUNwwzRrJF50974CowB6SzIUe+C3GxlfqmT13KbIRqR2aK2gFwjjc0iQT",
	"0bJc/yw0a6Ly0KJnwmt9EVRCWdpgzUs2YgHk0MnTIM09GBCmcNU1WEYANVDComVOkNQBLXtv9bRg1gYY",
	"VZ76dmuhDwjslQu8nWDPQ5tVTs7WgZ41hlstb7xf/vXji5d4hQautO9Ot+2gykPARQ4Scrrqy7T/nOd4",
	"XPP/TA1YDdQlmg+MQp0vp5Azj8rgWZKxcHcg8PU78Sd2ivZAaeJE+jLWNJEn2TNs8bi/YziSZs/NEHsf",
	"3F+Dozul6xxqJ37JKaiRn0RRwfQo7EGQSCGgMxrkHIBp/SmZU+YG02rRfwPS6fVq6e5K1mv/Oq8WbL5X",
	"qX2ZRr8/lRL9BoXluorjbn1xao1rW7+z1y+3uHeMklmJAEssd+M0+CMDvixUiGhMlcrFbiHMSBZJ3G35",
	"5ddmfH87x7qu1bBWG3FD0w26JLOZgA3KlHf3a3a/elRDKjaqJ9qphFg8gHG3ahHOyXLTZXvl5mELxb6e",
	"fcdUFefCnF+/Luuskwsq8mx4kiVJGy6/B83LUFGZfsmAK9evFCY9y+x90P/tVpIKftEQ5qpgr1QmLW1L",
	"GXq1HNkV95agZMMlYv2bYTUFyJ7sQdXnYzPtE0GnEi54Ghlg/PoUw/8NFHz89RK5q+eN8W+vv7Zw7uYy",
	"IE4YLG14l2a6HNTmE90l2zDT5TcpbqJbywtzzfhtJKtet36yieyTp6Wbr5/URPNtgPkKA8zpGhOTxwZl",
	"KLDvkzxd7stk3P1jjL5R38x6ERZAdC/rha5hlvCczNpSMtdoMHRoDKxfozN3i05KTT19m9CnWk0/a/0s",
	"v0LxdKun5Sq/1c5vtbOexf6/qJwq11Bv5XWAuuqpntJi6gac4yQgEQrhFqIkNWSkXos9nPEId/FCyrS7",
	"txepdYtEyO4L/4Wvq5Lda+2dy/zlFw1a9X03ZXP9SkdMGJmrD2kxHdoh6bQYt++RyM0cWBJTHgQLiQ5u",
	"313d/S8AAP//EFgikEo4AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
