// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3XLbNhZ+FQzamU1nKJmS5TTRzF4otpJqakuuLGc3rb0qTB5JqEmQBUA3asa3+wD7",
	"iPskO/jjj0jJspO0mdnmJrIIHhyc3+980AccJHGaMGBS4P4HnBJOYpDA9V+jEOI0kcCC9fewVt+EIAJO",
	"U0kThvv4ktFfM0C3sEYyQcBExgFx+DUDIREtXm6jCxKbdb9RuUJC/eXWXTEOMuNMoIAEKwgRB5EmTEAb",
	"nXO4U5qhMEsjGhAJKFgRvgTRvmLYw/CexGkEuI/VZq2jIx9e9Hy/Bd2XN61eJ+y1yLed561e7/nzo6Ne",
	"z/d9H3uYKtVXQELg2MOMxEpA6agtdVYPK/0ohxD3Jc/AwyJYQUyUEWLy/hTYUq5wv3t05OGYMvd3x8Ny",
	"nSqBQnLKlvj+/t69qk06yOQq4fR3mJrja6PzJAUuKegVJE4yJuvGHujvEWUo0DZ5Bu1l20NHvu+jv6Ov",
	"j/y2739TNop64uFFwmMilYmYfN7DWlsaZ3FZV8okLIHjew8HhIdzlsU3wOsqHBMeIvMQPesctjovUUiX",
	"VIrKvrjXqf7DHk6JlMCVjH9dXYUfOode5+X917hmLQ8HmZBJDHxOwwYF7EMVXEzSBQWOFjyJ0WsanBEu",
	"K2ooSa3e0fPGXe7uthzvDjhdqFijCUN3JMoAPTts9RoP2uke1s926PWaTwbvU8rX8zhhKlIaNzdLkF6C",
	"nnVanW5lw07XU8Fn3dd9yJd2wzUQvns/tQI9e/fu3bvKdl3/0C/t0fW7vaZtEh5ucZetD3rBXi7TK1vG",
	"rJt5VM7In4pNqxHjufSpRrJx+IYLqga6zndMbn6BQKqTHZNUZvzJqSoTFBgJpayNMyFRTGSwQsTVghAZ",
	"SR+fvilZx8BkozdmK0D2ORqdlLSruGDPIprrlWXa7Lu9VVIr91CTwYecJ3xq63/d3qAe178OkhDqxz0j",
	"wYoyaHEgIbmJAOm3kV7sYWDKhj/h0fjt4HR0Mp9NB+OL0Ww0GWMPnw/enQ3Hs/nwn+ej6fCk9M14Mpu/",
	"nlyO1Xfu1cHZ5HI8wx4+uTw/HR0PZsP56GR4dj6ZDcfH7+bfD99hD0+HP1wOL2bz8+nkeHhxMRq/wR4+",
	"G+lPc/VQbTR/PRqenlQkvbq8GI2HFxdzK6C078VsMBtiD5v952eji7PB7Pi7ktyT4flwfKK0UK+VdCqt",
	"nY3OhpNLJVdLHSgTzIfT6WSqt5oNp+PBqf3iuqGqxSAEWTbY/7ssJmzT+m71QwFjveSWN8WKyIIAhIkL",
	"F70LEgnI194kSQSEaeG1189NSG5L6nngINHOLowbMrSelapBxKmcB83lYmw6arJAHCRfI7tcNMvKi8ac",
	"NMj6xwpYnuW/EVEqMmVdQyKhJWmsjMyyKFIuckCn5uIbwm7nSk5jWXlF2O3fin1M4xyd7C3YFqFdsl0V",
	"fYRUDouMhbuEmhWPkXmX0J0S1fM95dkT7elDt/rJHgw4ELn3bmbxts0aEBvnCjc3wTXzJC+6eZe5vDh5",
	"OvgbnWwiiGasBWL7gavhapejZ9+ikKyFEV9Z8s2Tbb8DGDmrF9Do4c7q4dJgNb9tGstKs4yeuTIBIVok",
	"HMkVFW7TJskREXKuC/VcDVvLhDc51T5R9Uq9YCs7MF3dwITpg1Zh8F7Odbnb7iO1xpZEKpAaosIs+ogs",
	"2A5UJxqh7hFXpmjsm0lu9ZM1FpLITGxLLJlvZtcVsEb1fYMxBpez7ybT0Y8axhwPzmeXBtG8HoxO9Yfp",
	"8PXl+ER/fDsZmQ8O+DQ1/CwN968lOkDsG3sXFFVH993ArH2igTdAh063BwaLuWv7edXLvVTPzErhrVhu",
	"ExNcb0co2+FwSKTmI77msMB9/NVBweUcWMrhwMGcKmCqGVWuQJWHgpXRi8GYdh84NdWh/hGTkm3HjYOS",
	"639/0phkVPtypqS3Cd1u6ccdTaXPH3qw+nnUYsoWiZnkmCSBPpXl5QbnI3SRpWnC9dGr57HBjZZEwm9k",
	"jdRi1edSnqhIp2yJAsJDd2aB5Ion2XKFCIqT4BYpVKcWibWQELev2BX76ivkpJ7SBQTrIIIr1kK2oKL/",
	"/vs/qCip+k9XVPUfrpo+8I6ptJuLTE22apS6+BUbRBGKM2nRCgvThOokOZ9czL5B1taIMPTzBpH5MzJM",
	"p3J2aujUEpuqAkfLFO0rNoVMm0yVAVHha/NvXHVwjK16sMnaamZWUqnDybbS3KZvCk9hD98BF8aTnbbf",
	"9nWPToGRlOI+Pmz7bUuvrXRkH+SjjI7zRDTUkykI4HcgkMpYgRKGCHJlXA8SPGyjY12UBSIFAGO5H1Qx",
	"Bw9dMTeFbUDF3CAqeDxEWIgkJ0xQbUZl5pKrE259qmNr0Ig5yUICRxZ40gViicwLnjFm7qVRqDLCWeE8",
	"B3Jl1v6n5n5QLDnYYPXvr02ygpCvknDt0tDOxiQ1sUITdvCLUDbOx23tlBsiaKA+iCyOicKL+JX6qmo1",
	"5WsSZVBuBaZwV/jmJua4MhKUOV1N4VoKtkqtdrob3KchMgv4V+IZS/z8Q620Rt3fV+ucghj6C5MI2jxd",
	"v/NIg5bm9f6Hwmqu11fZCWPDDXrBr5EEuOt3ey2/0+oczTp+/9Dv+50f8eZgr99qkZvA2LQ8MzYI8H8s",
	"gyA30W31Vnkgy6V1uxV19Dv7XuJsDkHmCugW1pY+bvR2gairuLiMaZuNVcZP2tH7x80mjtOvNjeyEiNs",
	"d1tkUbRWu/d8/5GRRNkdiWg4L7BXHk05kWqo0zqVmbN6ToqFXqjV8f2KMTTl9ghrVCneBluM7Iau15SK",
	"mzbDi0eawcqZq5EgyXbboSBDCwPkehSgQokKkRL2WS1h60x1u57/8pEGyNv9/EY1eBBizgv0uNUWOzno",
	"wjwFmHDSc88pKJbnnmmcKj9VQWiwWzWnYyo09t8dts2Udil4N5gQDpoL0aqEdLEAO0WXI+zz+7MMTxO2",
	"iGggFVJwmaYRiNLkaK+U/2RpJ4EzEiENoLhhdTSSLzp73gFRgT0kWQrNOFiMja/VOwfuamkrUjs2F/kK",
	"hHG4o0kmonW5/llo1kbloUXPhDf6Oq2EsrTB2ldswgLIoZOnQZp7MSBM4aobsIQBaqGEReucoWkCWvb2",
	"78uCWVtgVHnq26+FPiKwN65B94I9j21WOcXdBHpq9wRqeev9+vdvX7zEG2R6pX33+l0HVR4DLnKQkPNl",
	"f0z7z3mOpzX/z9SA1UBd4hnBKNT74xRy5lEZvEgyFu7fBz+xSfT5S/Me0hfKpoRv1EqbNA9XSkdOHDjs",
	"fPDBfRqd3CvVl9A46UpOQY26JIoKhkP1XIJECgFd0CCffU3LS8mSMjeQVYvdG5BOr1drd9NSr3l1PinY",
	"fivT+FMc/esrNdMXv70qjrvzZ1c1jql+469/GuN+oZQsSsRPYjkLp8GvGfB1oUJEY6pULnYLYUGySOJ+",
	"xy//6Mb3d3OLda3GjdqIW5pu0SVZLARsUaa8u9+w+/WTCnGxUTPBTCXE4hFMs1WLcE7W267qK4T8Dmq5",
	"noynVBWlwpwbiacf53eFebIV+fdDBlwdcCP9NFI9+KD/2y/xCvbI0KGqIGzkn5a2I9lerSd2xYOJlmy5",
	"o2r+9VRDmtmTPSrHPjaePlFjLFX9P7PvFJeoxq/VwHsDBc95s0buTnFr5NlrhR1cpiFZ44TB2gZWCSvn",
	"YCFHyldsC1bOGWqHlGsRaa5v/oK61WusT4Z0P3lCuLnli0KK/4fA8Lw2X+aeoQwF9prewuZKtTCR9jA8",
	"1Dd026dowgKIHpyi0Q0sEp4PxztKRW2sRsfmaPrHTeauwklpqCNvE/qlVpHPWjfKV7JfbtWw3MdfNeML",
	"qxnWLw9UDBVjaLBxrdZUNdRbmsRrgpKnSUAiFMIdRElqhnq9Fns44xHu45WUaf/gIFLrVomQ/Rf+C19n",
	"o92r9uOp/BJZgxR9b0TZUl+NxoSpmXNZgPUcjuYa10emDYncIO6SmDLkLiQ6eHV/ff+/AAAA//+nKVu6",
	"2DQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
