// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xab3PbNtL/Khi0M48zQ8mULKeJZp4Xiq2kmtqSK8u5c2ufCpMrCTUJsgDoRs347X2A",
	"+4j3SW4AECQoUrbs5NLMXPMmMrnALvbvbxf8iIMkThMGTArc/4hTwkkMErj+axRCnCYSWLD+AdbqSQgi",
	"4DSVNGG4jy8Y/S0DdAtrJBMETGQcEIffMhAS0XJxG52T2ND9TuUKCfWXpbtiHGTGmUABCVYQIg4iTZiA",
	"NjrjcKckQ2GWRjQgElCwInwJon3FsIfhA4nTCHAfK2atw0MfXvV8vwXd1zetXifstch3nZetXu/ly8PD",
	"Xs/3fR97mCrRV0BC4NjDjMRqA+eoLXVWDyv5KIcQ9yXPwMMiWEFMlBJi8uEE2FKucL97eOjhmDL7d8fD",
	"cp2qDYXklC3x/f29XapVOsjkKuH0D5ia42ul8yQFLiloChInGZN1ZQ/0c0QZCrRO9qC9bHvo0Pd99P/o",
	"20O/7fsvXKWoNx5eJDwmUqmIyZc9rKWlcRa7slImYQkc33s4IDycsyy+AV4X4YjwEJmXaK9z0Oq8RiFd",
	"UikqfHGvU/2HPZwSKYGrPf5xdRV+7Bx4ndf33+KatjwcZEImMfA5DRsEyF8q52KSLihwtOBJjN7S4JRw",
	"WRFD7dTqHb5s5HJ3t+V4d8DpQvkaTRi6I1EGaO+g1Ws8aKd7UD/bgddrPhl8SClfz+OEKU9pZG5IkCZB",
	"e51Wp1th2Ol6yvly83Ufs2XOcA2EP8xPUaC9y8vLywq7rn/gOzy6frfXxCbh4RZz5flBE+xkMk3ZMmrd",
	"jCM3In8umVY9xrPhU/VkY/ANE1QVdF1wTG5+hUCqkx2RVGb82aEqExSYHZyojTMhUUxksELE5oIQmZ0+",
	"PXxTso6ByUZrzFaA8vdodOxIVzHBjkm0kCvLtNoftpYjVmGhJoUPOU/4NM//dX2Del1/HCQh1I97SoIV",
	"ZdDiQEJyEwHSq5Em9jAwpcOf8Wj8fnAyOp7PpoPx+Wg2moyxh88Gl6fD8Ww+/PvZaDo8dp6MJ7P528nF",
	"WD2zSwenk4vxDHv4+OLsZHQ0mA3no+Ph6dlkNhwfXc5/GF5iD0+HP14Mz2fzs+nkaHh+Phq/wx4+Helf",
	"c/VSMZq/HQ1P3K3PZ4PZEHvYsJifjs5PB7Oj752lx8Oz4fhYMVLLHLYO7Wx0OpxcKAn1rgN1yvlwOp1M",
	"NavZcDoenOQPrhsSVwxCkGWDir/PYsI2FWypH/OJ3BCWvMkdRBYEIIzprYMuSCSgoL1JkggI05vXlp8Z",
	"r9sWt/PAop4HCy1uCMJ64KkaEKdyHjRnhLEpmskCcZB8jXJy0bxXkRfmpGGvv62AFYH8OxFOHnFlDYmE",
	"lqSxUjLLokiZyGKZmolvCLudq30aM8cbwm7/r+RjauPoeOeN8zzz0N42UT5hVw6LjIUPbWoonrLnXUIf",
	"3FG933G//EQ72tBSP9uCAQcid+ZmiLcxawBlnCto3ITIzJsirxaF5OL8+Pn4bnS8CRKa4RSI7QeuumtO",
	"jva+QyFZC7N9heTFs3X/APaxWi/Rz+PF08NO7zS/beq8nHZFt1WZgBAtEo7kigrLtGnniAg514l6rvqp",
	"ZcKbjJq/UflKLcgzOzCd3cC46aNaYfBBznW6224jRZOnRCqQ6pPCLPqEKNiORScahO7gVyZp7BpJlvrZ",
	"EgtJZCa2BZYsmOV0JXJRdd/AiMHF7PvJdPSTRipHg7PZxdS8ML/147eD0Yn+MR2+vRgfOz8N6fvJyPml",
	"X1v00wQJsjTcPdtoF8pX7JxyVKbdlYGhfaYJNmCJDshHuou5BQZFXizsWI/dSmquaG4TNVxvxzDbMXFI",
	"pB5KfMthgfv4m/1yoLOfzx32LRCqQqqaUuUKVAIpRzOaGIxqdwFcUx0Mn9Au5QW7sVuyFfJP6pWMaF9P",
	"q/Q+ods1/bSjqfD5ogern0cRU7ZITDvHJAn0qfLh3OBshM6zNE24Pnr1PLlzoyWR8DtZI0WsKmHKE+Xp",
	"lC1RQHhozyyQXPEkW64QQXES3CKF+xSRWAsJcfuKXbFvvkF21xO6gGAdRHDFWihPuejf//wXKpOu/tOm",
	"Wv2HzbGPrDGZdpPIZOpcDKfOX7FBFKE4kzmeYWGaUB0kZ5Pz2QuU6xoRhn7ZmGb+gsy4Uxk7NTNVZ6Sq",
	"HEfvKdpXbAqZVplKA6IytC2e2Oxgx7bqxeboVo9nJZXanfJiW+j0XWkp7OE74MJYstP2276u4ikwklLc",
	"xwdtv53P2Fbas/eLZkf7eSIa8skUBPA7EEhFrEAJQwTZNK5bDR620ZFOygKREqKxwg4qmYOHrpjt0zbA",
	"ZKEQ5TweIixEkhMmqFajUrNj6oTnNtW+NWhEpWQhgaMcmtIFYoksEp5RZmGlUagiwmrhrIB67uj+5+Z6",
	"UJLsb4z2769NsIKQb5JwbcMw755JanyFJmz/V6F0XDTk2ig3RNBA/RBZHBOFKPEb9aiqNWVrEmXglgKT",
	"uCtD56bxcaVpcAe7eo6bz2Gr89VOd2MAaqaZJUB0ho3OkP6xUlqb399X85yCGPqBCQStnq7feaJCnY6+",
	"/7HUmq311fmF0eHGAMKvjRFw1+/2Wn6n1Tmcdfz+gd/3Oz/hzdZfr2qRm8Do1O0qGzbwf3JBkO35tlrL",
	"bdmK3brdijh6za43OZttkrkHuoV1PkNutHaJuavI2cW0zcpy8ZM29O5+s4nj9NLmQuaMhXNuiyyK1op7",
	"1+/u4Em7SVSdtTbIM7UXeQLdgKoJeUWFEO2V1YNWO1EPCUmjyKm+L5TgPd9/Ygi4to2p0BiwEgzFMNiM",
	"f7cNP4vhJd6QFHHQXbPO5SFdLCDvt4o06ppbjx0NSrkjEQ3nJZjdLtHmgNiRxeySY1nU6vh+E7ud3etR",
	"Y45yhrZ4V4/Z819/eb9S7VmIkkyqCrnpNUqqw52c5rMpSAJnJEIaO3Az8tAgtixqRfJHZdmVZCl0O57D",
	"S3yt1uzbq5WtIOXIXGQr/MHhjiaZiNZu6OeopI1cvK7boRt9neQADI1W2ldswgIoUIOn8YldGBCmIMUN",
	"5L0yaqGERetifNGEMfLbr68LYWxBEG7Ds1v1eEJwbVwD7lTxn5ruivlvU72vDdEVeevD+o/vXr3GG5Pm",
	"SuXq9bu2Sj+lrhb1sRggfZnKV7T4m3Wv92UzQTVVql7SGcKBEaj35QSy6lERvEgyFn7xlG1Vos/vtDpI",
	"X6iyRUR1E+/myjxoHs+Uti/ft7Bx/6P9NTq+V6IvobHJk5yC6vKIKhy2uVedP0EihYAuaFC0fabKp2RJ",
	"me1FqsnuHUgr15u1vYao57z6KCXYfmXR+CmK/vpItbPlt0flcR/87Kg2XqnfeOtPQ+wXOsnCmXkkebtu",
	"JfgtA74uRYhoTJXIJbcQFiSLJO53fPejE99/eKxWl2rcKI24pekWWZLFQsAWYVzufgP362cl4pJR82yV",
	"SojFE4asuViEc7Ledo9dmUU/MFWtB+MJVUmpVOdG4OnXxUVaEWxl/P2YAVcH3Ag/3SDtf9T/7RZ45eDE",
	"TAJVQtiIP73bA8H2Zj3JKR4NtGTLBU7z10MNYZaf7Ekx9qn+9JkKo5P1/8y6U94wGrtWHe8dlCO+mzWy",
	"F25bPS+fqD8wxjPzxThhsM4dy8HKBVgokPIV24KVi+GsRco1jzQ3F39B3eoNzmdDup89IGzf8lUhxf9B",
	"YHhW6y8Ly1CGgvwOO4fNlWxhPO1xeKgvp7Z30YQFED3aRaMbWCS8aI4fSBW1thodmaPpL3/MmN7u0pBH",
	"3if0a80i/9W84d5Gfr1ZI599/JUzvrKckdvlkYyhfAwNNm6UmrKGWqWHeE1Q8iQJSIRCuIMoSU1Tr2mx",
	"hzMe4T5eSZn29/cjRbdKhOy/8l/5OhpzXrUvi4r7Uw1S9JUJZUt9KxgTpnrOZQnWCzhaSFxvmTZ25AZx",
	"O9u4kLvc0cKr++v7/wQAAP//MXQSm9gzAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
