// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bank "github.com/DanielPopoola/ficmart-payment-gateway/internal/infrastructure/bank"

	mock "github.com/stretchr/testify/mock"
)

// MockBankClient is an autogenerated mock type for the BankClient type
type MockBankClient struct {
	mock.Mock
}

type MockBankClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankClient) EXPECT() *MockBankClient_Expecter {
	return &MockBankClient_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Authorize(ctx context.Context, req bank.AuthorizationRequest, idempotencyKey string) (*bank.AuthorizationResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *bank.AuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.AuthorizationRequest, string) (*bank.AuthorizationResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.AuthorizationRequest, string) *bank.AuthorizationResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.AuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.AuthorizationRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockBankClient_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - req bank.AuthorizationRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Authorize(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Authorize_Call {
	return &MockBankClient_Authorize_Call{Call: _e.mock.On("Authorize", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Authorize_Call) Run(run func(ctx context.Context, req bank.AuthorizationRequest, idempotencyKey string)) *MockBankClient_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bank.AuthorizationRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Authorize_Call) Return(_a0 *bank.AuthorizationResponse, _a1 error) *MockBankClient_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Authorize_Call) RunAndReturn(run func(context.Context, bank.AuthorizationRequest, string) (*bank.AuthorizationResponse, error)) *MockBankClient_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// Capture provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Capture(ctx context.Context, req bank.CaptureRequest, idempotencyKey string) (*bank.CaptureResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 *bank.CaptureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.CaptureRequest, string) (*bank.CaptureResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.CaptureRequest, string) *bank.CaptureResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.CaptureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.CaptureRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type MockBankClient_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - ctx context.Context
//   - req bank.CaptureRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Capture(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Capture_Call {
	return &MockBankClient_Capture_Call{Call: _e.mock.On("Capture", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Capture_Call) Run(run func(ctx context.Context, req bank.CaptureRequest, idempotencyKey string)) *MockBankClient_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bank.CaptureRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Capture_Call) Return(_a0 *bank.CaptureResponse, _a1 error) *MockBankClient_Capture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Capture_Call) RunAndReturn(run func(context.Context, bank.CaptureRequest, string) (*bank.CaptureResponse, error)) *MockBankClient_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorization provides a mock function with given fields: ctx, authID
func (_m *MockBankClient) GetAuthorization(ctx context.Context, authID string) (*bank.AuthorizationResponse, error) {
	ret := _m.Called(ctx, authID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorization")
	}

	var r0 *bank.AuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*bank.AuthorizationResponse, error)); ok {
		return rf(ctx, authID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *bank.AuthorizationResponse); ok {
		r0 = rf(ctx, authID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.AuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_GetAuthorization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorization'
type MockBankClient_GetAuthorization_Call struct {
	*mock.Call
}

// GetAuthorization is a helper method to define mock.On call
//   - ctx context.Context
//   - authID string
func (_e *MockBankClient_Expecter) GetAuthorization(ctx interface{}, authID interface{}) *MockBankClient_GetAuthorization_Call {
	return &MockBankClient_GetAuthorization_Call{Call: _e.mock.On("GetAuthorization", ctx, authID)}
}

func (_c *MockBankClient_GetAuthorization_Call) Run(run func(ctx context.Context, authID string)) *MockBankClient_GetAuthorization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBankClient_GetAuthorization_Call) Return(_a0 *bank.AuthorizationResponse, _a1 error) *MockBankClient_GetAuthorization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_GetAuthorization_Call) RunAndReturn(run func(context.Context, string) (*bank.AuthorizationResponse, error)) *MockBankClient_GetAuthorization_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Refund(ctx context.Context, req bank.RefundRequest, idempotencyKey string) (*bank.RefundResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 *bank.RefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.RefundRequest, string) (*bank.RefundResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.RefundRequest, string) *bank.RefundResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.RefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.RefundRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockBankClient_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - req bank.RefundRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Refund(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Refund_Call {
	return &MockBankClient_Refund_Call{Call: _e.mock.On("Refund", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Refund_Call) Run(run func(ctx context.Context, req bank.RefundRequest, idempotencyKey string)) *MockBankClient_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bank.RefundRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Refund_Call) Return(_a0 *bank.RefundResponse, _a1 error) *MockBankClient_Refund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Refund_Call) RunAndReturn(run func(context.Context, bank.RefundRequest, string) (*bank.RefundResponse, error)) *MockBankClient_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// Void provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *MockBankClient) Void(ctx context.Context, req bank.VoidRequest, idempotencyKey string) (*bank.VoidResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 *bank.VoidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.VoidRequest, string) (*bank.VoidResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.VoidRequest, string) *bank.VoidResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.VoidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.VoidRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBankClient_Void_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Void'
type MockBankClient_Void_Call struct {
	*mock.Call
}

// Void is a helper method to define mock.On call
//   - ctx context.Context
//   - req bank.VoidRequest
//   - idempotencyKey string
func (_e *MockBankClient_Expecter) Void(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockBankClient_Void_Call {
	return &MockBankClient_Void_Call{Call: _e.mock.On("Void", ctx, req, idempotencyKey)}
}

func (_c *MockBankClient_Void_Call) Run(run func(ctx context.Context, req bank.VoidRequest, idempotencyKey string)) *MockBankClient_Void_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bank.VoidRequest), args[2].(string))
	})
	return _c
}

func (_c *MockBankClient_Void_Call) Return(_a0 *bank.VoidResponse, _a1 error) *MockBankClient_Void_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBankClient_Void_Call) RunAndReturn(run func(context.Context, bank.VoidRequest, string) (*bank.VoidResponse, error)) *MockBankClient_Void_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBankClient creates a new instance of MockBankClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankClient {
	mock := &MockBankClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
