// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/DanielPopoola/ficmart-payment-gateway/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Authorizer is an autogenerated mock type for the Authorizer type
type Authorizer struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: ctx, orderID, customerID, idempotencyKey, amount, cardNumber, cvv, expiryMonth, expiryYear
func (_m *Authorizer) Authorize(ctx context.Context, orderID string, customerID string, idempotencyKey string, amount int64, cardNumber string, cvv string, expiryMonth int, expiryYear int) (*domain.Payment, error) {
	ret := _m.Called(ctx, orderID, customerID, idempotencyKey, amount, cardNumber, cvv, expiryMonth, expiryYear)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, string, int, int) (*domain.Payment, error)); ok {
		return rf(ctx, orderID, customerID, idempotencyKey, amount, cardNumber, cvv, expiryMonth, expiryYear)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, string, string, int, int) *domain.Payment); ok {
		r0 = rf(ctx, orderID, customerID, idempotencyKey, amount, cardNumber, cvv, expiryMonth, expiryYear)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64, string, string, int, int) error); ok {
		r1 = rf(ctx, orderID, customerID, idempotencyKey, amount, cardNumber, cvv, expiryMonth, expiryYear)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reconcile provides a mock function with given fields: ctx, p
func (_m *Authorizer) Reconcile(ctx context.Context, p *domain.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorizer creates a new instance of Authorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authorizer {
	mock := &Authorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
