// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/DanielPopoola/ficmart-payment-gateway/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Refunder is an autogenerated mock type for the Refunder type
type Refunder struct {
	mock.Mock
}

// Reconcile provides a mock function with given fields: ctx, p
func (_m *Refunder) Reconcile(ctx context.Context, p *domain.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Refund provides a mock function with given fields: ctx, paymentID, amount, idempotencyKey
func (_m *Refunder) Refund(ctx context.Context, paymentID uuid.UUID, amount int64, idempotencyKey string) (*domain.Payment, error) {
	ret := _m.Called(ctx, paymentID, amount, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string) (*domain.Payment, error)); ok {
		return rf(ctx, paymentID, amount, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string) *domain.Payment); ok {
		r0 = rf(ctx, paymentID, amount, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, string) error); ok {
		r1 = rf(ctx, paymentID, amount, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefunder creates a new instance of Refunder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefunder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Refunder {
	mock := &Refunder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
