// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bank "github.com/DanielPopoola/ficmart-payment-gateway/internal/bank"

	mock "github.com/stretchr/testify/mock"
)

// BankPort is an autogenerated mock type for the BankPort type
type BankPort struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *BankPort) Authorize(ctx context.Context, req bank.AuthorizationRequest, idempotencyKey string) (*bank.AuthorizationResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *bank.AuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.AuthorizationRequest, string) (*bank.AuthorizationResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.AuthorizationRequest, string) *bank.AuthorizationResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.AuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.AuthorizationRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Capture provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *BankPort) Capture(ctx context.Context, req bank.CaptureRequest, idempotencyKey string) (*bank.CaptureResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 *bank.CaptureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.CaptureRequest, string) (*bank.CaptureResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.CaptureRequest, string) *bank.CaptureResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.CaptureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.CaptureRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthorization provides a mock function with given fields: ctx, authID
func (_m *BankPort) GetAuthorization(ctx context.Context, authID string) (*bank.AuthorizationResponse, error) {
	ret := _m.Called(ctx, authID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorization")
	}

	var r0 *bank.AuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*bank.AuthorizationResponse, error)); ok {
		return rf(ctx, authID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *bank.AuthorizationResponse); ok {
		r0 = rf(ctx, authID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.AuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCapture provides a mock function with given fields: ctx, captureID
func (_m *BankPort) GetCapture(ctx context.Context, captureID string) (*bank.CaptureResponse, error) {
	ret := _m.Called(ctx, captureID)

	if len(ret) == 0 {
		panic("no return value specified for GetCapture")
	}

	var r0 *bank.CaptureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*bank.CaptureResponse, error)); ok {
		return rf(ctx, captureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *bank.CaptureResponse); ok {
		r0 = rf(ctx, captureID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.CaptureResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, captureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefund provides a mock function with given fields: ctx, refundID
func (_m *BankPort) GetRefund(ctx context.Context, refundID string) (*bank.RefundResponse, error) {
	ret := _m.Called(ctx, refundID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefund")
	}

	var r0 *bank.RefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*bank.RefundResponse, error)); ok {
		return rf(ctx, refundID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *bank.RefundResponse); ok {
		r0 = rf(ctx, refundID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.RefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refundID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refund provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *BankPort) Refund(ctx context.Context, req bank.RefundRequest, idempotencyKey string) (*bank.RefundResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 *bank.RefundResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.RefundRequest, string) (*bank.RefundResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.RefundRequest, string) *bank.RefundResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.RefundResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.RefundRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Void provides a mock function with given fields: ctx, req, idempotencyKey
func (_m *BankPort) Void(ctx context.Context, req bank.VoidRequest, idempotencyKey string) (*bank.VoidResponse, error) {
	ret := _m.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Void")
	}

	var r0 *bank.VoidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bank.VoidRequest, string) (*bank.VoidResponse, error)); ok {
		return rf(ctx, req, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bank.VoidRequest, string) *bank.VoidResponse); ok {
		r0 = rf(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.VoidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bank.VoidRequest, string) error); ok {
		r1 = rf(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBankPort creates a new instance of BankPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankPort {
	mock := &BankPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
