// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@ficmart.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authorize": {
            "post": {
                "description": "Reserve funds on a customer's card for a specific order. Returns immediately with payment status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Authorize a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique key to prevent duplicate requests",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payment authorization details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AuthorizeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Payment authorized successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "202": {
                        "description": "Request is being processed (duplicate idempotency key)",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict - duplicate or invalid state",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/capture": {
            "post": {
                "description": "Charge the funds that were previously authorized. The payment must be in AUTHORIZED status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Capture a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique key to prevent duplicate requests",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payment capture details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CaptureRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment captured successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or amount mismatch",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Payment not found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Payment not in capturable state",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/payments/customer/{customerID}": {
            "get": {
                "description": "Retrieve all payment records for a specific customer with pagination support",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "Get payments by customer ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FicMart Customer ID",
                        "name": "customerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of payments",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid customer ID",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/payments/order/{orderID}": {
            "get": {
                "description": "Retrieve the payment record associated with a specific FicMart order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queries"
                ],
                "summary": "Get payment by order ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FicMart Order ID",
                        "name": "orderID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid order ID",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Payment not found for this order",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/refund": {
            "post": {
                "description": "Return money to the customer for a previously captured payment. The payment must be in CAPTURED status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Refund a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique key to prevent duplicate requests",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payment refund details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefundRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment refunded successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or amount",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Payment not found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Payment not in refundable state",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "412": {
                        "description": "Missing required bank capture ID",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/void": {
            "post": {
                "description": "Cancel an authorized payment before it has been captured. Releases the hold on funds.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Void a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique key to prevent duplicate requests",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payment void details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.VoidRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment voided successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Payment not found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Payment not in voidable state",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "412": {
                        "description": "Missing required bank authorization ID",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_AMOUNT"
                },
                "message": {
                    "type": "string",
                    "example": "Amount must be greater than zero"
                }
            }
        },
        "handler.APIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "error": {
                    "$ref": "#/definitions/handler.APIError"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.AuthorizeRequest": {
            "type": "object",
            "required": [
                "amount",
                "card_number",
                "customer_id",
                "cvv",
                "expiry_month",
                "expiry_year",
                "order_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 5000
                },
                "card_number": {
                    "type": "string",
                    "maxLength": 19,
                    "minLength": 13,
                    "example": "4111111111111111"
                },
                "customer_id": {
                    "type": "string",
                    "example": "cust-67890"
                },
                "cvv": {
                    "type": "string",
                    "example": "123"
                },
                "expiry_month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 12
                },
                "expiry_year": {
                    "type": "integer",
                    "minimum": 2024,
                    "example": 2030
                },
                "order_id": {
                    "type": "string",
                    "example": "order-12345"
                }
            }
        },
        "handler.CaptureRequest": {
            "type": "object",
            "required": [
                "amount",
                "payment_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 5000
                },
                "payment_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "handler.RefundRequest": {
            "type": "object",
            "required": [
                "amount",
                "payment_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 5000
                },
                "payment_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "handler.VoidRequest": {
            "type": "object",
            "required": [
                "payment_id"
            ],
            "properties": {
                "payment_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "FicMart Payment Gateway API",
	Description:      "Payment gateway for processing authorizations, captures, voids, and refunds",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
